<a href="https://colab.research.google.com/github/raghav5102/ML-prediction-models/blob/main/FutureSale.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PREDICT FUTURE SALE PRICE

In [ ]:

from sklearn.ensemble import RandomForestRegressor
from IPython.display import display 
from sklearn import metrics

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('train(1).csv')
df.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [ ]:
df.shape

(1460, 81)

In [ ]:
dft=pd.read_csv('test(1).csv')
dft.head()

     Id  MSSubClass MSZoning  ...  YrSold  SaleType SaleCondition
0  1461          20       RH  ...    2010        WD        Normal
1  1462          20       RL  ...    2010        WD        Normal
2  1463          60       RL  ...    2010        WD        Normal
3  1464          60       RL  ...    2010        WD        Normal
4  1465         120       RL  ...    2010        WD        Normal

[5 rows x 80 columns]

In [ ]:
dft.shape

(1459, 80)

In [ ]:
for col_name in df.columns:
    if(df[col_name].dtype == 'object'):
        df[col_name]= df[col_name].astype('category')
        df[col_name] = df[col_name].cat.codes

df.fillna(method='pad',inplace=True)

In [ ]:
from sklearn.model_selection import train_test_split
y=df.SalePrice
df=df.drop('SalePrice',axis=1)
X=df


X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0)

(2919, 80)

In [ ]:
clf=RandomForestRegressor(n_jobs=-1,n_estimators=1000)

In [ ]:
df.head()

   Id  MSSubClass  MSZoning  ...  YrSold  SaleType  SaleCondition
0   1          60         3  ...    2008         8              4
1   2          20         3  ...    2007         8              4
2   3          60         3  ...    2008         8              4
3   4          70         3  ...    2006         8              0
4   5          60         3  ...    2008         8              4

[5 rows x 80 columns]

In [ ]:
clf.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=1000, n_jobs=-1, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

TypeError: ignored

In [ ]:
clf.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=1000, n_jobs=-1, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [ ]:
for col_name in dft.columns:
    if(dft[col_name].dtype == 'object'):
        dft[col_name]= dft[col_name].astype('category')
        dft[col_name] = dft[col_name].cat.codes

In [ ]:
dft.head()

     Id  MSSubClass  MSZoning  ...  YrSold  SaleType  SaleCondition
0  1461          20         2  ...    2010         8              4
1  1462          20         3  ...    2010         8              4
2  1463          60         3  ...    2010         8              4
3  1464          60         3  ...    2010         8              4
4  1465         120         3  ...    2010         8              4

[5 rows x 80 columns]

In [ ]:
import math
def rmse(x,y): 
  return math.sqrt(((x-y)**2).mean())
def print_score(m):
    res = [rmse(m.predict(X_train), y_train),
           
           m.score(X_train, y_train),]
    if hasattr(m, 'oob_score_'): res.append(m.oob_score_)
    print(res)

In [ ]:
print_score(clf)

[0.051597834574076115, 0.9833032631665328]

In [ ]:
dft.fillna(method='pad',inplace=True)
X_test=dft
y_test=clf.predict(X_test)

In [ ]:
dft['SalePrice']=y_test

In [ ]:
dft.head()

     Id  MSSubClass  MSZoning  ...  SaleType  SaleCondition  SalePrice
0  1461          20         2  ...         8              4  11.723632
1  1462          20         3  ...         8              4  11.931582
2  1463          60         3  ...         8              4  12.085508
3  1464          60         3  ...         8              4  12.109200
4  1465         120         3  ...         8              4  12.191359

[5 rows x 81 columns]

In [ ]:
dft = dft.set_index('Id')
dft.head()

      MSSubClass  MSZoning  LotFrontage  ...  SaleType  SaleCondition  SalePrice
Id                                       ...
1461          20         2         80.0  ...         8              4  11.723632
1462          20         3         81.0  ...         8              4  11.931582
1463          60         3         74.0  ...         8              4  12.085508
1464          60         3         78.0  ...         8              4  12.109200
1465         120         3         43.0  ...         8              4  12.191359

[5 rows x 80 columns]

In [ ]:
solution=pd.DataFrame(dft['SalePrice']).reset_index()
solution

        Id  SalePrice
0     1461  11.723632
1     1462  11.931582
2     1463  12.085508
3     1464  12.109200
4     1465  12.191359
...    ...        ...
1454  2915  11.304796
1455  2916  11.327641
1456  2917  11.930808
1457  2918  11.634379
1458  2919  12.360125

[1459 rows x 2 columns]

In [ ]:
from google.colab import drive
drive.mount('drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at drive

In [ ]:
solution.to_csv('sale.csv',index=False)
!cp sale.csv "drive/My Drive/"